//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccABalanceSheet
    {
        public string AC1Name { get; set; }
        public string AC2Name { get; set; }
        public double Amount { get; set; }
        public System.DateTime GenerateTime { get; set; }
    }
}
