//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccVoucherMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccVoucherMaster()
        {
            this.AccVoucherDetails = new HashSet<AccVoucherDetail>();
        }
    
        public int Id { get; set; }
        public string VoucherNo { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public int CompanyId { get; set; }
        public int VoucherTypeId { get; set; }
        public string PaymentTo { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<int> ChequeBankId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> EntryType { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> ConversionRate { get; set; }
        public string Narration { get; set; }
        public Nullable<int> VMonth { get; set; }
        public Nullable<int> VYear { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<bool> MApproval { get; set; }
        public Nullable<bool> GApproval { get; set; }
        public Nullable<bool> DApproval { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AccCurrencyInfo AccCurrencyInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccVoucherDetail> AccVoucherDetails { get; set; }
        public virtual AccVoucherType AccVoucherType { get; set; }
        public virtual CmnBank CmnBank { get; set; }
    }
}
