//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmnEmailTracking
    {
        public int TrackingID { get; set; }
        public int MenuID { get; set; }
        public int SenderEmployeeID { get; set; }
        public string SenderEmailAddress { get; set; }
        public int ReceiverEmployeeID { get; set; }
        public string ReceiverEmailAddress { get; set; }
        public string TransactionNo { get; set; }
        public long TransactionID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> DBID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
