//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmnOrganogram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CmnOrganogram()
        {
            this.CmnOrganogram1 = new HashSet<CmnOrganogram>();
            this.CmnWorkFlowMasters = new HashSet<CmnWorkFlowMaster>();
            this.PrdBWSlists = new HashSet<PrdBWSlist>();
            this.PrdDefectTypes = new HashSet<PrdDefectType>();
            this.InvRChallanMasters = new HashSet<InvRChallanMaster>();
            this.PrdWastages = new HashSet<PrdWastage>();
            this.PurchasePOMasters = new HashSet<PurchasePOMaster>();
            this.PrdWeavingMachinConfigs = new HashSet<PrdWeavingMachinConfig>();
            this.MntMachineMaintenanceOrders = new HashSet<MntMachineMaintenanceOrder>();
            this.CmnItemMasters = new HashSet<CmnItemMaster>();
            this.SalHDOMasters = new HashSet<SalHDOMaster>();
            this.SalLCMasters = new HashSet<SalLCMaster>();
            this.InvIssueMasters = new HashSet<InvIssueMaster>();
            this.PrdDyingConsumptionChemicals = new HashSet<PrdDyingConsumptionChemical>();
            this.MntMachineSchedules = new HashSet<MntMachineSchedule>();
        }
    
        public int OrganogramID { get; set; }
        public string CustomCode { get; set; }
        public string OrganogramName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool IsBranch { get; set; }
        public bool IsDepartment { get; set; }
        public string ProcessOutput { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmnOrganogram> CmnOrganogram1 { get; set; }
        public virtual CmnOrganogram CmnOrganogram2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmnWorkFlowMaster> CmnWorkFlowMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdBWSlist> PrdBWSlists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdDefectType> PrdDefectTypes { get; set; }
        public virtual PrdDyingProcess PrdDyingProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRChallanMaster> InvRChallanMasters { get; set; }
        public virtual CmnCompany CmnCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWastage> PrdWastages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasePOMaster> PurchasePOMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingMachinConfig> PrdWeavingMachinConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MntMachineMaintenanceOrder> MntMachineMaintenanceOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmnItemMaster> CmnItemMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalHDOMaster> SalHDOMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalLCMaster> SalLCMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvIssueMaster> InvIssueMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdDyingConsumptionChemical> PrdDyingConsumptionChemicals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MntMachineSchedule> MntMachineSchedules { get; set; }
    }
}
