//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmnUserAuthentication
    {
        public int AuthenticationID { get; set; }
        public int UserID { get; set; }
        public string LoginID { get; set; }
        public string LoginEmail { get; set; }
        public string LoginPhone { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> TimezoneID { get; set; }
        public Nullable<bool> AllowMultipleLogin { get; set; }
        public string NoOfLogin { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
