//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmnUOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CmnUOM()
        {
            this.CmnUserExperiences = new HashSet<CmnUserExperience>();
            this.PrdDyingChemicalSetups = new HashSet<PrdDyingChemicalSetup>();
            this.PrdDyingChemicalSetupDetails = new HashSet<PrdDyingChemicalSetupDetail>();
            this.PrdSizingChemicalSetups = new HashSet<PrdSizingChemicalSetup>();
            this.PrdSizingChemicalSetupDetails = new HashSet<PrdSizingChemicalSetupDetail>();
            this.InvRChallanDetails = new HashSet<InvRChallanDetail>();
            this.PrdDyingConsumptionDetails = new HashSet<PrdDyingConsumptionDetail>();
            this.PrdWastageDetails = new HashSet<PrdWastageDetail>();
            this.PurchasePODetails = new HashSet<PurchasePODetail>();
            this.InvMrrDetails = new HashSet<InvMrrDetail>();
            this.PrdBOMSizes = new HashSet<PrdBOMSize>();
            this.PrdBOMDyings = new HashSet<PrdBOMDying>();
            this.PrdPreCostingDyings = new HashSet<PrdPreCostingDying>();
            this.PrdPreCostingSizes = new HashSet<PrdPreCostingSize>();
            this.PrdPreCostingYarns = new HashSet<PrdPreCostingYarn>();
            this.InvRequisitionDetails = new HashSet<InvRequisitionDetail>();
            this.CmnItemMasters = new HashSet<CmnItemMaster>();
            this.PrdSizingChemicalconsumptionDetails = new HashSet<PrdSizingChemicalconsumptionDetail>();
            this.InvMrrQcDetails = new HashSet<InvMrrQcDetail>();
            this.InvIssueDetails = new HashSet<InvIssueDetail>();
        }
    
        public int UOMID { get; set; }
        public string CustomCode { get; set; }
        public string UOMName { get; set; }
        public string UOMShortName { get; set; }
        public Nullable<int> UOMGroupID { get; set; }
        public Nullable<decimal> ConversionValue { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnUOMGroup CmnUOMGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmnUserExperience> CmnUserExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdDyingChemicalSetup> PrdDyingChemicalSetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdDyingChemicalSetupDetail> PrdDyingChemicalSetupDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingChemicalSetup> PrdSizingChemicalSetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingChemicalSetupDetail> PrdSizingChemicalSetupDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRChallanDetail> InvRChallanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdDyingConsumptionDetail> PrdDyingConsumptionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWastageDetail> PrdWastageDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasePODetail> PurchasePODetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMrrDetail> InvMrrDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdBOMSize> PrdBOMSizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdBOMDying> PrdBOMDyings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdPreCostingDying> PrdPreCostingDyings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdPreCostingSize> PrdPreCostingSizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdPreCostingYarn> PrdPreCostingYarns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRequisitionDetail> InvRequisitionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmnItemMaster> CmnItemMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingChemicalconsumptionDetail> PrdSizingChemicalconsumptionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMrrQcDetail> InvMrrQcDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvIssueDetail> InvIssueDetails { get; set; }
    }
}
