//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmnUserEducation
    {
        public long UserEducationRecordID { get; set; }
        public string CustomCode { get; set; }
        public int UserID { get; set; }
        public string Description { get; set; }
        public int DegreeID { get; set; }
        public string Result { get; set; }
        public Nullable<int> ResultUOMID { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<bool> IsScorePercent { get; set; }
        public Nullable<int> ScoreUOMID { get; set; }
        public Nullable<decimal> ScoreOutOf { get; set; }
        public Nullable<System.DateTime> YearPass { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> EducationDuration { get; set; }
        public Nullable<int> EducationDurationUoMID { get; set; }
        public string Institute { get; set; }
        public string InstituteAddress { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> DBID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
        public bool Transfer { get; set; }
    }
}
