//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmnUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CmnUser()
        {
            this.InvRChallanMasters = new HashSet<InvRChallanMaster>();
            this.MntMachineMaintenanceOrders = new HashSet<MntMachineMaintenanceOrder>();
            this.MntMachineMaintenanceOrders1 = new HashSet<MntMachineMaintenanceOrder>();
            this.PrdBallMRRDetails = new HashSet<PrdBallMRRDetail>();
            this.PrdBallMRRDetails1 = new HashSet<PrdBallMRRDetail>();
            this.PrdDyingChemicalSetups = new HashSet<PrdDyingChemicalSetup>();
            this.PrdFinishingMRRMasters = new HashSet<PrdFinishingMRRMaster>();
            this.PrdLCBMRRDetails = new HashSet<PrdLCBMRRDetail>();
            this.PrdLCBMRRDetails1 = new HashSet<PrdLCBMRRDetail>();
            this.PurchasePOMasters = new HashSet<PurchasePOMaster>();
            this.SalBookingMasters = new HashSet<SalBookingMaster>();
            this.SalBookingMasters1 = new HashSet<SalBookingMaster>();
            this.MntMachineSchedules = new HashSet<MntMachineSchedule>();
        }
    
        public int UserID { get; set; }
        public string CustomCode { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> UserDesignationID { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public Nullable<int> UserTitleID { get; set; }
        public Nullable<int> AcDetailID { get; set; }
        public string UserFirstName { get; set; }
        public string UserMiddleName { get; set; }
        public string UserLastName { get; set; }
        public string UserFullName { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string SpouseNane { get; set; }
        public string ParAddress2 { get; set; }
        public string ParAddress1 { get; set; }
        public Nullable<int> ParCountryID { get; set; }
        public Nullable<int> ParStateID { get; set; }
        public Nullable<int> ParCityID { get; set; }
        public string PreAddress2 { get; set; }
        public string PreAddress1 { get; set; }
        public Nullable<int> PreCountryID { get; set; }
        public Nullable<int> PreStateID { get; set; }
        public Nullable<int> PreCityID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public string UniqueIdentity { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PassportNO { get; set; }
        public string ImageUrl { get; set; }
        public string SignatureUrl { get; set; }
        public string FingerUrl { get; set; }
        public string NID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnUserGroup CmnUserGroup { get; set; }
        public virtual CmnUserType CmnUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRChallanMaster> InvRChallanMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MntMachineMaintenanceOrder> MntMachineMaintenanceOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MntMachineMaintenanceOrder> MntMachineMaintenanceOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdBallMRRDetail> PrdBallMRRDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdBallMRRDetail> PrdBallMRRDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdDyingChemicalSetup> PrdDyingChemicalSetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdFinishingMRRMaster> PrdFinishingMRRMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdLCBMRRDetail> PrdLCBMRRDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdLCBMRRDetail> PrdLCBMRRDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasePOMaster> PurchasePOMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalBookingMaster> SalBookingMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalBookingMaster> SalBookingMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MntMachineSchedule> MntMachineSchedules { get; set; }
    }
}
