//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmnUserExperience
    {
        public long UserExperienceRecordID { get; set; }
        public string CustomCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExperienceID { get; set; }
        public Nullable<System.DateTime> ExperienceStartDate { get; set; }
        public Nullable<System.DateTime> ExperienceEndDate { get; set; }
        public Nullable<decimal> ExperienceDuration { get; set; }
        public Nullable<int> ExperienceDurationUOMID { get; set; }
        public string Institute { get; set; }
        public string InstituteAddress { get; set; }
        public Nullable<decimal> IncomeAmount { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> CostCenterID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public int DBID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
        public bool Transfer { get; set; }
    
        public virtual CmnUOM CmnUOM { get; set; }
    }
}
