//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmnWorkFlowTransactionTran
    {
        public long RecordID { get; set; }
        public string CustomCode { get; set; }
        public Nullable<long> MenuID { get; set; }
        public Nullable<long> WFDID { get; set; }
        public Nullable<long> WFMID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string WFDStatusID { get; set; }
        public Nullable<bool> IsActve { get; set; }
        public Nullable<long> TarTeamID { get; set; }
        public Nullable<long> TUserID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> TeamID { get; set; }
        public Nullable<int> EntrySequence { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> BeginEndTrac { get; set; }
        public Nullable<bool> IsTeam { get; set; }
        public Nullable<long> AppDECBy { get; set; }
        public Nullable<bool> IsDeclied { get; set; }
        public Nullable<bool> IsDeclinedDisable { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string Bcomment { get; set; }
        public string Ccomment { get; set; }
        public string Notification { get; set; }
        public string Description { get; set; }
        public Nullable<long> OrganogramID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<int> DBID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
        public bool Transfer { get; set; }
    }
}
