//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_Entities : DbContext
    {
        public ERP_Entities()
            : base("name=ERP_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccAC1> AccAC1 { get; set; }
        public virtual DbSet<AccAC2> AccAC2 { get; set; }
        public virtual DbSet<AccAC3> AccAC3 { get; set; }
        public virtual DbSet<AccAC4> AccAC4 { get; set; }
        public virtual DbSet<AccACDetail> AccACDetails { get; set; }
        public virtual DbSet<AccCurrencyInfo> AccCurrencyInfoes { get; set; }
        public virtual DbSet<AccVoucherDetail> AccVoucherDetails { get; set; }
        public virtual DbSet<AccVoucherType> AccVoucherTypes { get; set; }
        public virtual DbSet<AccABalanceSheet> AccABalanceSheets { get; set; }
        public virtual DbSet<AccVoucherDetailTemp> AccVoucherDetailTemps { get; set; }
        public virtual DbSet<AccVoucherMasterTemp> AccVoucherMasterTemps { get; set; }
        public virtual DbSet<HRMShift> HRMShifts { get; set; }
        public virtual DbSet<HRMShiftBreak> HRMShiftBreaks { get; set; }
        public virtual DbSet<HRMShiftHoliday> HRMShiftHolidays { get; set; }
        public virtual DbSet<HRMShiftPlan> HRMShiftPlans { get; set; }
        public virtual DbSet<HRMShiftWeekend> HRMShiftWeekends { get; set; }
        public virtual DbSet<RndConsumptionMaster> RndConsumptionMasters { get; set; }
        public virtual DbSet<RndConsumptionType> RndConsumptionTypes { get; set; }
        public virtual DbSet<SalLCDetail> SalLCDetails { get; set; }
        public virtual DbSet<SalPPBADetail> SalPPBADetails { get; set; }
        public virtual DbSet<SalPPBAMaster> SalPPBAMasters { get; set; }
        public virtual DbSet<SalPPBillingMaster> SalPPBillingMasters { get; set; }
        public virtual DbSet<AMonthList> AMonthLists { get; set; }
        public virtual DbSet<AppErrorLog> AppErrorLogs { get; set; }
        public virtual DbSet<AYearList> AYearLists { get; set; }
        public virtual DbSet<CmnAddressCity> CmnAddressCities { get; set; }
        public virtual DbSet<CmnAddressCountry> CmnAddressCountries { get; set; }
        public virtual DbSet<CmnAddressState> CmnAddressStates { get; set; }
        public virtual DbSet<CmnAddressType> CmnAddressTypes { get; set; }
        public virtual DbSet<CmnBankAdvising> CmnBankAdvisings { get; set; }
        public virtual DbSet<CmnBankBranch> CmnBankBranches { get; set; }
        public virtual DbSet<CmnBatch> CmnBatches { get; set; }
        public virtual DbSet<CmnCombo> CmnComboes { get; set; }
        public virtual DbSet<CmnComboType> CmnComboTypes { get; set; }
        public virtual DbSet<CmnCompanyAddress> CmnCompanyAddresses { get; set; }
        public virtual DbSet<CmnCustomCode> CmnCustomCodes { get; set; }
        public virtual DbSet<CmnCustomCodeAutoNo> CmnCustomCodeAutoNoes { get; set; }
        public virtual DbSet<CmnCustomCodeDetail> CmnCustomCodeDetails { get; set; }
        public virtual DbSet<CmnDataBaseLocation> CmnDataBaseLocations { get; set; }
        public virtual DbSet<CmnDocumentPath> CmnDocumentPaths { get; set; }
        public virtual DbSet<CmnItemCondition> CmnItemConditions { get; set; }
        public virtual DbSet<CmnItemFinishingProcess> CmnItemFinishingProcesses { get; set; }
        public virtual DbSet<CmnItemGrade> CmnItemGrades { get; set; }
        public virtual DbSet<CmnItemModel> CmnItemModels { get; set; }
        public virtual DbSet<CmnItemSize> CmnItemSizes { get; set; }
        public virtual DbSet<CmnItemSpecification> CmnItemSpecifications { get; set; }
        public virtual DbSet<CmnItemStyleMaster> CmnItemStyleMasters { get; set; }
        public virtual DbSet<CmnItemType> CmnItemTypes { get; set; }
        public virtual DbSet<CmnItemYear> CmnItemYears { get; set; }
        public virtual DbSet<CmnMenuPermission> CmnMenuPermissions { get; set; }
        public virtual DbSet<CmnMenuTableMapping> CmnMenuTableMappings { get; set; }
        public virtual DbSet<CmnMenuType> CmnMenuTypes { get; set; }
        public virtual DbSet<CmnModulePermission> CmnModulePermissions { get; set; }
        public virtual DbSet<CmnOrganogram> CmnOrganograms { get; set; }
        public virtual DbSet<CmnStatu> CmnStatus { get; set; }
        public virtual DbSet<CmnTransactionType> CmnTransactionTypes { get; set; }
        public virtual DbSet<CmnUOM> CmnUOMs { get; set; }
        public virtual DbSet<CmnUOMGroup> CmnUOMGroups { get; set; }
        public virtual DbSet<CMnUserAddress> CMnUserAddresses { get; set; }
        public virtual DbSet<CmnUserAuthentication> CmnUserAuthentications { get; set; }
        public virtual DbSet<CmnUserDegreeList> CmnUserDegreeLists { get; set; }
        public virtual DbSet<CmnUserDesignation> CmnUserDesignations { get; set; }
        public virtual DbSet<CmnUserEducation> CmnUserEducations { get; set; }
        public virtual DbSet<CmnUserExperience> CmnUserExperiences { get; set; }
        public virtual DbSet<CmnUserExperienceList> CmnUserExperienceLists { get; set; }
        public virtual DbSet<CmnUserType> CmnUserTypes { get; set; }
        public virtual DbSet<CmnWFApprovalPendingList> CmnWFApprovalPendingLists { get; set; }
        public virtual DbSet<CmnWorkFlowMaster> CmnWorkFlowMasters { get; set; }
        public virtual DbSet<CmnWorkFlowTransaction> CmnWorkFlowTransactions { get; set; }
        public virtual DbSet<CmnItemFinishingWeight> CmnItemFinishingWeights { get; set; }
        public virtual DbSet<PrdBWSlist> PrdBWSlists { get; set; }
        public virtual DbSet<PrdDefectList> PrdDefectLists { get; set; }
        public virtual DbSet<PrdDefectType> PrdDefectTypes { get; set; }
        public virtual DbSet<PrdDyingChemicalSetup> PrdDyingChemicalSetups { get; set; }
        public virtual DbSet<PrdDyingChemicalSetupDetail> PrdDyingChemicalSetupDetails { get; set; }
        public virtual DbSet<PrdOutputUnit> PrdOutputUnits { get; set; }
        public virtual DbSet<PrdDyingOperation> PrdDyingOperations { get; set; }
        public virtual DbSet<PrdDyingProcess> PrdDyingProcesses { get; set; }
        public virtual DbSet<PrdBallMachineSetup> PrdBallMachineSetups { get; set; }
        public virtual DbSet<PrdDyingMachineOperation> PrdDyingMachineOperations { get; set; }
        public virtual DbSet<PrdDyingMachinePart> PrdDyingMachineParts { get; set; }
        public virtual DbSet<RndConsumptionDetail> RndConsumptionDetails { get; set; }
        public virtual DbSet<CmnUserJobContract> CmnUserJobContracts { get; set; }
        public virtual DbSet<PrdBallMRRBreakage> PrdBallMRRBreakages { get; set; }
        public virtual DbSet<PrdBallMRRBreakageM> PrdBallMRRBreakageMs { get; set; }
        public virtual DbSet<PrdBallMRRMachineStopM> PrdBallMRRMachineStopMs { get; set; }
        public virtual DbSet<PrdBallMRRMaster> PrdBallMRRMasters { get; set; }
        public virtual DbSet<PrdInternalIssue> PrdInternalIssues { get; set; }
        public virtual DbSet<PrdInternalIssueDetail> PrdInternalIssueDetails { get; set; }
        public virtual DbSet<PrdDyingMRRSet> PrdDyingMRRSets { get; set; }
        public virtual DbSet<PrdDyingMeasurement> PrdDyingMeasurements { get; set; }
        public virtual DbSet<PrdSizingChemicalSetup> PrdSizingChemicalSetups { get; set; }
        public virtual DbSet<PrdSizingChemicalSetupDetail> PrdSizingChemicalSetupDetails { get; set; }
        public virtual DbSet<PrdSizingMachineSetup> PrdSizingMachineSetups { get; set; }
        public virtual DbSet<PrdSizingMRRBreakage> PrdSizingMRRBreakages { get; set; }
        public virtual DbSet<PrdSizingMRRBreakageM> PrdSizingMRRBreakageMs { get; set; }
        public virtual DbSet<PrdSizingMRRConsumption> PrdSizingMRRConsumptions { get; set; }
        public virtual DbSet<PrdSizingMRRDetail> PrdSizingMRRDetails { get; set; }
        public virtual DbSet<PrdSizingMRRMachineStopM> PrdSizingMRRMachineStopMs { get; set; }
        public virtual DbSet<PrdSizingMRRMaster> PrdSizingMRRMasters { get; set; }
        public virtual DbSet<PrdSizingBeamQuality> PrdSizingBeamQualities { get; set; }
        public virtual DbSet<PrdSizingMRRMachineStop> PrdSizingMRRMachineStops { get; set; }
        public virtual DbSet<PrdLCBMRRBreakageM> PrdLCBMRRBreakageMs { get; set; }
        public virtual DbSet<PrdLCBMRRMachineStopM> PrdLCBMRRMachineStopMs { get; set; }
        public virtual DbSet<PrdLCBMRRMaster> PrdLCBMRRMasters { get; set; }
        public virtual DbSet<PrdLCBMRRBreakage> PrdLCBMRRBreakages { get; set; }
        public virtual DbSet<InvIntegrationType> InvIntegrationTypes { get; set; }
        public virtual DbSet<InvRChallanDetail> InvRChallanDetails { get; set; }
        public virtual DbSet<InvRChallanMaster> InvRChallanMasters { get; set; }
        public virtual DbSet<PrdSizingBeamIssueDetail> PrdSizingBeamIssueDetails { get; set; }
        public virtual DbSet<CmnWorkFlowDetail> CmnWorkFlowDetails { get; set; }
        public virtual DbSet<CmnItemCount> CmnItemCounts { get; set; }
        public virtual DbSet<PrdWeavingLine> PrdWeavingLines { get; set; }
        public virtual DbSet<PrdWeavingLoomStop> PrdWeavingLoomStops { get; set; }
        public virtual DbSet<PrdWeavingMachineBook> PrdWeavingMachineBooks { get; set; }
        public virtual DbSet<PrdWeavingMachineSetup> PrdWeavingMachineSetups { get; set; }
        public virtual DbSet<PrdWeavingLoomStopDetail> PrdWeavingLoomStopDetails { get; set; }
        public virtual DbSet<CmnCompany> CmnCompanies { get; set; }
        public virtual DbSet<AccVoucherMaster> AccVoucherMasters { get; set; }
        public virtual DbSet<PrdDyingConsumptionChemicalM> PrdDyingConsumptionChemicalMs { get; set; }
        public virtual DbSet<PrdDyingConsumptionDetail> PrdDyingConsumptionDetails { get; set; }
        public virtual DbSet<PrdDyingConsumptionMaster> PrdDyingConsumptionMasters { get; set; }
        public virtual DbSet<PrdWeavingLoomData> PrdWeavingLoomDatas { get; set; }
        public virtual DbSet<PrdWeavingMRRMaster> PrdWeavingMRRMasters { get; set; }
        public virtual DbSet<PrdFinishingMRRMaster> PrdFinishingMRRMasters { get; set; }
        public virtual DbSet<PrdFinishingMRRShrinkage> PrdFinishingMRRShrinkages { get; set; }
        public virtual DbSet<PrdFinishingChemicalSetup> PrdFinishingChemicalSetups { get; set; }
        public virtual DbSet<PrdFinishingChemicalSetupDetail> PrdFinishingChemicalSetupDetails { get; set; }
        public virtual DbSet<PrdFinishingDefectPoint> PrdFinishingDefectPoints { get; set; }
        public virtual DbSet<PrdFinishingInspactionDetail> PrdFinishingInspactionDetails { get; set; }
        public virtual DbSet<PrdFinishingInspactionMaster> PrdFinishingInspactionMasters { get; set; }
        public virtual DbSet<PrdFinishingQADetail> PrdFinishingQADetails { get; set; }
        public virtual DbSet<PrdFinishingQAMaster> PrdFinishingQAMasters { get; set; }
        public virtual DbSet<PrdWastage> PrdWastages { get; set; }
        public virtual DbSet<PrdWastageDetail> PrdWastageDetails { get; set; }
        public virtual DbSet<CmnBank> CmnBanks { get; set; }
        public virtual DbSet<PurchaseConsumer> PurchaseConsumers { get; set; }
        public virtual DbSet<PurchaseConsumerChargeType> PurchaseConsumerChargeTypes { get; set; }
        public virtual DbSet<PurchaseCostAccessment> PurchaseCostAccessments { get; set; }
        public virtual DbSet<PurchaseCostClearing> PurchaseCostClearings { get; set; }
        public virtual DbSet<PurchaseCostClearingMaster> PurchaseCostClearingMasters { get; set; }
        public virtual DbSet<PurchaseCostMaster> PurchaseCostMasters { get; set; }
        public virtual DbSet<PurchaseCostTransport> PurchaseCostTransports { get; set; }
        public virtual DbSet<PurchaseCostTransportMaster> PurchaseCostTransportMasters { get; set; }
        public virtual DbSet<PurchaseCSDetail> PurchaseCSDetails { get; set; }
        public virtual DbSet<PurchaseFR> PurchaseFRs { get; set; }
        public virtual DbSet<PurchasePIDetail> PurchasePIDetails { get; set; }
        public virtual DbSet<PurchasePIMaster> PurchasePIMasters { get; set; }
        public virtual DbSet<PurchasePODetail> PurchasePODetails { get; set; }
        public virtual DbSet<PurchaseQuotation> PurchaseQuotations { get; set; }
        public virtual DbSet<PurchaseTax> PurchaseTaxes { get; set; }
        public virtual DbSet<PurchaseTaxCategory> PurchaseTaxCategories { get; set; }
        public virtual DbSet<PurchaseTC> PurchaseTCs { get; set; }
        public virtual DbSet<PurchaseCostAccessmentDetail> PurchaseCostAccessmentDetails { get; set; }
        public virtual DbSet<PurchaseCostAccessmentMaster> PurchaseCostAccessmentMasters { get; set; }
        public virtual DbSet<PurchaseCostClearingDetail> PurchaseCostClearingDetails { get; set; }
        public virtual DbSet<PurchaseCostTransportDetail> PurchaseCostTransportDetails { get; set; }
        public virtual DbSet<SalHDODetail> SalHDODetails { get; set; }
        public virtual DbSet<SalPIDetail> SalPIDetails { get; set; }
        public virtual DbSet<prdFinishingProcessPriceSetup> prdFinishingProcessPriceSetups { get; set; }
        public virtual DbSet<CmnUserTeam> CmnUserTeams { get; set; }
        public virtual DbSet<CmnuserTeamDetail> CmnuserTeamDetails { get; set; }
        public virtual DbSet<CmnModule> CmnModules { get; set; }
        public virtual DbSet<InvStockTransit> InvStockTransits { get; set; }
        public virtual DbSet<InvMrrDetail> InvMrrDetails { get; set; }
        public virtual DbSet<SalIncoterm> SalIncoterms { get; set; }
        public virtual DbSet<InvMrrMaster> InvMrrMasters { get; set; }
        public virtual DbSet<PurchaseCSMaster> PurchaseCSMasters { get; set; }
        public virtual DbSet<PurchasePOMaster> PurchasePOMasters { get; set; }
        public virtual DbSet<InvGrrDetail> InvGrrDetails { get; set; }
        public virtual DbSet<CmnUserGroup> CmnUserGroups { get; set; }
        public virtual DbSet<CmnWorkFlowTransactionTran> CmnWorkFlowTransactionTrans { get; set; }
        public virtual DbSet<CmnACCIntegration> CmnACCIntegrations { get; set; }
        public virtual DbSet<PurchaseQuotationMaster> PurchaseQuotationMasters { get; set; }
        public virtual DbSet<CmnMenu> CmnMenus { get; set; }
        public virtual DbSet<CmnItemColor> CmnItemColors { get; set; }
        public virtual DbSet<CmnItemGroup> CmnItemGroups { get; set; }
        public virtual DbSet<PrdFinishingProcess> PrdFinishingProcesses { get; set; }
        public virtual DbSet<CmnLot> CmnLots { get; set; }
        public virtual DbSet<RndYarnCR> RndYarnCRs { get; set; }
        public virtual DbSet<RndYarnCRDetail> RndYarnCRDetails { get; set; }
        public virtual DbSet<PrdFinishingType> PrdFinishingTypes { get; set; }
        public virtual DbSet<CmnTermsCondition> CmnTermsConditions { get; set; }
        public virtual DbSet<PrdBOMMaster> PrdBOMMasters { get; set; }
        public virtual DbSet<PrdBOMSize> PrdBOMSizes { get; set; }
        public virtual DbSet<SalBookingMaster> SalBookingMasters { get; set; }
        public virtual DbSet<PurchasePOTerm> PurchasePOTerms { get; set; }
        public virtual DbSet<PrdBOMDying> PrdBOMDyings { get; set; }
        public virtual DbSet<PrdWeavingMachinConfig> PrdWeavingMachinConfigs { get; set; }
        public virtual DbSet<PrdWeavingMachineConfigDetail> PrdWeavingMachineConfigDetails { get; set; }
        public virtual DbSet<MntMachineMaintenanceOrder> MntMachineMaintenanceOrders { get; set; }
        public virtual DbSet<PrdBallMRRMachineStop> PrdBallMRRMachineStops { get; set; }
        public virtual DbSet<PrdBallMRRDetail> PrdBallMRRDetails { get; set; }
        public virtual DbSet<PrdPreCostingDetail> PrdPreCostingDetails { get; set; }
        public virtual DbSet<PrdPreCostingDying> PrdPreCostingDyings { get; set; }
        public virtual DbSet<PrdPreCostingFinishing> PrdPreCostingFinishings { get; set; }
        public virtual DbSet<PrdPreCostingMaster> PrdPreCostingMasters { get; set; }
        public virtual DbSet<PrdPreCostingSize> PrdPreCostingSizes { get; set; }
        public virtual DbSet<PrdPreCostingYarn> PrdPreCostingYarns { get; set; }
        public virtual DbSet<PrdLCBMRRDetail> PrdLCBMRRDetails { get; set; }
        public virtual DbSet<PrdLCBMRRMachineStop> PrdLCBMRRMachineStops { get; set; }
        public virtual DbSet<InvRequisitionMaster> InvRequisitionMasters { get; set; }
        public virtual DbSet<PrdSizingBeamIssue> PrdSizingBeamIssues { get; set; }
        public virtual DbSet<CmnEmailTracking> CmnEmailTrackings { get; set; }
        public virtual DbSet<PrdDyingMRRSetDetail> PrdDyingMRRSetDetails { get; set; }
        public virtual DbSet<InvRequisitionDetail> InvRequisitionDetails { get; set; }
        public virtual DbSet<PrdWeavingLoomDetailData> PrdWeavingLoomDetailDatas { get; set; }
        public virtual DbSet<PrdFinishingPackingList> PrdFinishingPackingLists { get; set; }
        public virtual DbSet<PrdFinishingPackingListDetail> PrdFinishingPackingListDetails { get; set; }
        public virtual DbSet<SalBookingDetail> SalBookingDetails { get; set; }
        public virtual DbSet<CmnDocument> CmnDocuments { get; set; }
        public virtual DbSet<CmnUser> CmnUsers { get; set; }
        public virtual DbSet<CmnItemCoating> CmnItemCoatings { get; set; }
        public virtual DbSet<CmnItemMaster> CmnItemMasters { get; set; }
        public virtual DbSet<CmnItemOverDyed> CmnItemOverDyeds { get; set; }
        public virtual DbSet<SalFDODetail> SalFDODetails { get; set; }
        public virtual DbSet<CmnUserWiseCompany> CmnUserWiseCompanies { get; set; }
        public virtual DbSet<PrdSetMaster> PrdSetMasters { get; set; }
        public virtual DbSet<PrdBallMRRConsumption> PrdBallMRRConsumptions { get; set; }
        public virtual DbSet<SalDCDetail> SalDCDetails { get; set; }
        public virtual DbSet<SalDCMaster> SalDCMasters { get; set; }
        public virtual DbSet<SalHDOMaster> SalHDOMasters { get; set; }
        public virtual DbSet<SalLCMaster> SalLCMasters { get; set; }
        public virtual DbSet<SalPIMaster> SalPIMasters { get; set; }
        public virtual DbSet<SalFDOMaster> SalFDOMasters { get; set; }
        public virtual DbSet<PrdDyingMachineSetup> PrdDyingMachineSetups { get; set; }
        public virtual DbSet<PrdDyingMachineSetupDetail> PrdDyingMachineSetupDetails { get; set; }
        public virtual DbSet<PrdDyingMRRBeamDetail> PrdDyingMRRBeamDetails { get; set; }
        public virtual DbSet<PrdDyingMRRDetail> PrdDyingMRRDetails { get; set; }
        public virtual DbSet<PrdDyingMRRMaster> PrdDyingMRRMasters { get; set; }
        public virtual DbSet<PrdDyingOperationSetup> PrdDyingOperationSetups { get; set; }
        public virtual DbSet<PrdDyingOperationSetupMaster> PrdDyingOperationSetupMasters { get; set; }
        public virtual DbSet<PrdSizingChemicalConsumption> PrdSizingChemicalConsumptions { get; set; }
        public virtual DbSet<PrdSizingChemicalconsumptionDetail> PrdSizingChemicalconsumptionDetails { get; set; }
        public virtual DbSet<InvMrrQcDetail> InvMrrQcDetails { get; set; }
        public virtual DbSet<InvMrrQcMaster> InvMrrQcMasters { get; set; }
        public virtual DbSet<SalSalesInvoiceDetail> SalSalesInvoiceDetails { get; set; }
        public virtual DbSet<SalSalesInvoiceMaster> SalSalesInvoiceMasters { get; set; }
        public virtual DbSet<PrdFinishingConsumptionMaster> PrdFinishingConsumptionMasters { get; set; }
        public virtual DbSet<PrdFinishingConsumptionDetail> PrdFinishingConsumptionDetails { get; set; }
        public virtual DbSet<InvStockDetail> InvStockDetails { get; set; }
        public virtual DbSet<InvStockMaster> InvStockMasters { get; set; }
        public virtual DbSet<InvIssueDetail> InvIssueDetails { get; set; }
        public virtual DbSet<InvIssueMaster> InvIssueMasters { get; set; }
        public virtual DbSet<PrdSetSetup> PrdSetSetups { get; set; }
        public virtual DbSet<PrdDyingConsumptionChemical> PrdDyingConsumptionChemicals { get; set; }
        public virtual DbSet<InvGrrMaster> InvGrrMasters { get; set; }
        public virtual DbSet<AccCostCenterInfo> AccCostCenterInfoes { get; set; }
        public virtual DbSet<PurchaseQuotationDetail> PurchaseQuotationDetails { get; set; }
        public virtual DbSet<CmnItemBrand> CmnItemBrands { get; set; }
        public virtual DbSet<MntMachineSchedule> MntMachineSchedules { get; set; }
        public virtual DbSet<MntMachineScheduleDetail> MntMachineScheduleDetails { get; set; }
        public virtual DbSet<MntMachineScheduleMType> MntMachineScheduleMTypes { get; set; }
        public virtual DbSet<MntMaintananceType> MntMaintananceTypes { get; set; }
    }
}
