//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMShift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRMShift()
        {
            this.PrdSizingMRRMachineStops = new HashSet<PrdSizingMRRMachineStop>();
            this.PrdFinishingMRRMasters = new HashSet<PrdFinishingMRRMaster>();
            this.PrdBallMRRMachineStops = new HashSet<PrdBallMRRMachineStop>();
            this.PrdBallMRRDetails = new HashSet<PrdBallMRRDetail>();
            this.PrdLCBMRRDetails = new HashSet<PrdLCBMRRDetail>();
            this.PrdLCBMRRMachineStops = new HashSet<PrdLCBMRRMachineStop>();
            this.PrdWeavingLoomDetailDatas = new HashSet<PrdWeavingLoomDetailData>();
            this.PrdDyingMRRMasters = new HashSet<PrdDyingMRRMaster>();
        }
    
        public int ShiftID { get; set; }
        public string ShiftName { get; set; }
        public int Sequence { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsRosterRequired { get; set; }
        public Nullable<decimal> RosterDuration { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingMRRMachineStop> PrdSizingMRRMachineStops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdFinishingMRRMaster> PrdFinishingMRRMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdBallMRRMachineStop> PrdBallMRRMachineStops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdBallMRRDetail> PrdBallMRRDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdLCBMRRDetail> PrdLCBMRRDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdLCBMRRMachineStop> PrdLCBMRRMachineStops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingLoomDetailData> PrdWeavingLoomDetailDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdDyingMRRMaster> PrdDyingMRRMasters { get; set; }
    }
}
