//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvGrrMaster
    {
        public long GrrID { get; set; }
        public string GrrNo { get; set; }
        public string ManualGrrNo { get; set; }
        public System.DateTime GrrDate { get; set; }
        public string RefCHNo { get; set; }
        public Nullable<System.DateTime> RefCHDate { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<long> RequisitionID { get; set; }
        public string SprNo { get; set; }
        public Nullable<long> IssueID { get; set; }
        public Nullable<long> CHID { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<long> POID { get; set; }
        public string PONo { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<bool> IsQcCompleted { get; set; }
        public bool IsMrrCompleted { get; set; }
        public int CompanyID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
