//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvGrrDetail
    {
        public long GrrDetailID { get; set; }
        public long GrrID { get; set; }
        public long ItemID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AdditionalQty { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> DisAmount { get; set; }
        public Nullable<int> PackingUnitID { get; set; }
        public Nullable<int> WeightUnitID { get; set; }
        public int UnitID { get; set; }
        public Nullable<decimal> PackingQty { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<long> LotID { get; set; }
        public Nullable<long> BatchID { get; set; }
        public Nullable<decimal> QcRemainingQty { get; set; }
        public Nullable<decimal> QcRemainingAdditionalQty { get; set; }
        public Nullable<bool> IsPercent { get; set; }
        public Nullable<bool> IsQcCompleted { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
