//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvIssueMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvIssueMaster()
        {
            this.InvIssueDetails = new HashSet<InvIssueDetail>();
        }
    
        public long IssueID { get; set; }
        public string IssueNo { get; set; }
        public int IssueTypeID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<long> ChallanID { get; set; }
        public Nullable<long> GRRID { get; set; }
        public Nullable<long> QCID { get; set; }
        public Nullable<long> MRRID { get; set; }
        public Nullable<long> RequisitionID { get; set; }
        public string RequisitionNo { get; set; }
        public Nullable<int> ToDepartmentID { get; set; }
        public Nullable<int> ToCompanyID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<long> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<long> IssueBy { get; set; }
        public int CompanyID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnCompany CmnCompany { get; set; }
        public virtual CmnOrganogram CmnOrganogram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvIssueDetail> InvIssueDetails { get; set; }
    }
}
