//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMrrMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvMrrMaster()
        {
            this.InvMrrDetails = new HashSet<InvMrrDetail>();
        }
    
        public long MrrID { get; set; }
        public string MrrNo { get; set; }
        public System.DateTime MrrDate { get; set; }
        public string ManualMRRNo { get; set; }
        public string MRRCertificateNo { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> MrrTypeID { get; set; }
        public Nullable<long> GrrID { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<long> RequisitionID { get; set; }
        public string ReqNo { get; set; }
        public Nullable<long> IssueID { get; set; }
        public Nullable<long> CHID { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<long> POID { get; set; }
        public string PONo { get; set; }
        public Nullable<long> MrrQcID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<bool> IsStoreCompleted { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsAccountsCompleted { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<long> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> FromDepartmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMrrDetail> InvMrrDetails { get; set; }
    }
}
