//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMrrQcMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvMrrQcMaster()
        {
            this.InvMrrQcDetails = new HashSet<InvMrrQcDetail>();
        }
    
        public long MrrQcID { get; set; }
        public string MrrQcNo { get; set; }
        public System.DateTime MrrQcDate { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<long> RequisitionID { get; set; }
        public string QCCertificateNo { get; set; }
        public string DocURL { get; set; }
        public long SPLID { get; set; }
        public long CIRID { get; set; }
        public int SPLTypeID { get; set; }
        public int CIRTypeID { get; set; }
        public int GrrID { get; set; }
        public string GrrNo { get; set; }
        public Nullable<long> CHID { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<long> POID { get; set; }
        public string PONo { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<bool> IsMrrCompleted { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public int CompanyID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMrrQcDetail> InvMrrQcDetails { get; set; }
    }
}
