//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvRChallanMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvRChallanMaster()
        {
            this.InvRChallanDetails = new HashSet<InvRChallanDetail>();
        }
    
        public long CHID { get; set; }
        public string CHNo { get; set; }
        public Nullable<System.DateTime> CHDate { get; set; }
        public string RefCHNo { get; set; }
        public Nullable<System.DateTime> RefCHDate { get; set; }
        public string DocURL { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> CHTypeID { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<long> RequisitionID { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<long> POID { get; set; }
        public Nullable<int> LoadingPortID { get; set; }
        public Nullable<int> DischargePortID { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual AccCurrencyInfo AccCurrencyInfo { get; set; }
        public virtual CmnOrganogram CmnOrganogram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRChallanDetail> InvRChallanDetails { get; set; }
        public virtual CmnCompany CmnCompany { get; set; }
        public virtual CmnUser CmnUser { get; set; }
    }
}
