//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvRequisitionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvRequisitionMaster()
        {
            this.PurchasePOMasters = new HashSet<PurchasePOMaster>();
            this.InvRequisitionDetails = new HashSet<InvRequisitionDetail>();
        }
    
        public long RequisitionID { get; set; }
        public string RequisitionNo { get; set; }
        public string ManualRequisitionNo { get; set; }
        public System.DateTime RequisitionDate { get; set; }
        public int RequisitionTypeID { get; set; }
        public long RequisitionBy { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> ToCompanyID { get; set; }
        public Nullable<int> ToDepartmentID { get; set; }
        public Nullable<System.DateTime> EstDate { get; set; }
        public Nullable<int> EstTime { get; set; }
        public Nullable<bool> IsUrgent { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> IsGrrComplete { get; set; }
        public bool IsComplete { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnCompany CmnCompany { get; set; }
        public virtual CmnTransactionType CmnTransactionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasePOMaster> PurchasePOMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvRequisitionDetail> InvRequisitionDetails { get; set; }
    }
}
