//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdBallMRRDetail
    {
        public long BalMRRDetailID { get; set; }
        public long BalMRRID { get; set; }
        public Nullable<long> YarnCountID { get; set; }
        public Nullable<long> LotID { get; set; }
        public Nullable<int> OutputUnitID { get; set; }
        public Nullable<long> BallConsumptionID { get; set; }
        public Nullable<long> BalMachineStopID { get; set; }
        public Nullable<int> TotalStop { get; set; }
        public Nullable<long> BallBreackageMasterID { get; set; }
        public Nullable<int> TotalBreakage { get; set; }
        public Nullable<decimal> SetLength { get; set; }
        public Nullable<long> MachineID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> MachineSpeed { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<int> ShiftEngineerID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> WarpingDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
        public bool IsIssued { get; set; }
    
        public virtual HRMShift HRMShift { get; set; }
        public virtual PrdBallMRRMaster PrdBallMRRMaster { get; set; }
        public virtual PrdOutputUnit PrdOutputUnit { get; set; }
        public virtual CmnUser CmnUser { get; set; }
        public virtual CmnUser CmnUser1 { get; set; }
        public virtual PrdBallMRRConsumption PrdBallMRRConsumption { get; set; }
    }
}
