//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdDyingOperationSetup
    {
        public long OperationSetupID { get; set; }
        public Nullable<long> SetupID { get; set; }
        public long ItemID { get; set; }
        public Nullable<long> ChemicalItemID { get; set; }
        public int DyingProcessID { get; set; }
        public int OperationID { get; set; }
        public Nullable<decimal> MinQty { get; set; }
        public Nullable<decimal> MaxQty { get; set; }
        public Nullable<int> UnitID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnItemMaster CmnItemMaster { get; set; }
        public virtual CmnItemMaster CmnItemMaster1 { get; set; }
        public virtual PrdDyingOperation PrdDyingOperation { get; set; }
        public virtual PrdDyingOperationSetupMaster PrdDyingOperationSetupMaster { get; set; }
        public virtual PrdDyingProcess PrdDyingProcess { get; set; }
    }
}
