//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdFinishingPackingList
    {
        public long PackingID { get; set; }
        public string PackingNo { get; set; }
        public Nullable<int> PackingTypeID { get; set; }
        public System.DateTime PackingDate { get; set; }
        public bool IsDCComplete { get; set; }
        public bool IsFDOComplete { get; set; }
        public long PIID { get; set; }
        public long FinishingMRRID { get; set; }
        public long ItemID { get; set; }
        public string Remarks { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual PrdFinishingMRRMaster PrdFinishingMRRMaster { get; set; }
        public virtual CmnItemMaster CmnItemMaster { get; set; }
        public virtual SalPIMaster SalPIMaster { get; set; }
    }
}
