//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdFinishingInspactionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdFinishingInspactionMaster()
        {
            this.PrdFinishingInspactionDetails = new HashSet<PrdFinishingInspactionDetail>();
            this.PrdFinishingQADetails = new HashSet<PrdFinishingQADetail>();
        }
    
        public long InspactionID { get; set; }
        public string InspactionNo { get; set; }
        public Nullable<long> FinishingMRRID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> SetID { get; set; }
        public Nullable<long> WeivingMRRID { get; set; }
        public Nullable<long> SizeMRRID { get; set; }
        public Nullable<int> MachineConfigID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> PlateID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsQAComplete { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdFinishingInspactionDetail> PrdFinishingInspactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdFinishingQADetail> PrdFinishingQADetails { get; set; }
    }
}
