//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdFinishingPackingListDetail
    {
        public long PackingDetailID { get; set; }
        public long PackingID { get; set; }
        public long QADetailID { get; set; }
        public string Shade { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> GWeight { get; set; }
        public Nullable<decimal> NWeight { get; set; }
        public Nullable<decimal> Shipment { get; set; }
        public Nullable<decimal> FiniWidth { get; set; }
        public Nullable<decimal> WPercent { get; set; }
        public Nullable<int> DefectPointID { get; set; }
        public Nullable<bool> IsNotDeliverable { get; set; }
        public string Remarks { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual PrdFinishingDefectPoint PrdFinishingDefectPoint { get; set; }
        public virtual PrdFinishingPackingListDetail PrdFinishingPackingListDetail1 { get; set; }
        public virtual PrdFinishingPackingListDetail PrdFinishingPackingListDetail2 { get; set; }
    }
}
