//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdFinishingQADetail
    {
        public long QADetailID { get; set; }
        public long QAID { get; set; }
        public long InspactionDateilID { get; set; }
        public long InspactionID { get; set; }
        public Nullable<decimal> LPercent { get; set; }
        public Nullable<decimal> WPercent { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<bool> IsNotDeliverable { get; set; }
        public string Remarks { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual PrdFinishingInspactionDetail PrdFinishingInspactionDetail { get; set; }
        public virtual PrdFinishingInspactionMaster PrdFinishingInspactionMaster { get; set; }
        public virtual PrdFinishingQAMaster PrdFinishingQAMaster { get; set; }
    }
}
