//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdFinishingMRRMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdFinishingMRRMaster()
        {
            this.PrdFinishingMRRShrinkages = new HashSet<PrdFinishingMRRShrinkage>();
            this.PrdFinishingPackingLists = new HashSet<PrdFinishingPackingList>();
        }
    
        public long FinishingMRRID { get; set; }
        public string FinishingMRRNo { get; set; }
        public Nullable<int> FinishingMRRTypeID { get; set; }
        public Nullable<System.DateTime> FinishingMRRDate { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> SetID { get; set; }
        public Nullable<long> SizeMRRID { get; set; }
        public Nullable<long> WeavingMRRID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<int> FinishingTypeID { get; set; }
        public Nullable<long> MachineID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<int> ShiftEngineerID { get; set; }
        public string Remarks { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual HRMShift HRMShift { get; set; }
        public virtual PrdFinishingMRRMaster PrdFinishingMRRMaster1 { get; set; }
        public virtual PrdFinishingMRRMaster PrdFinishingMRRMaster2 { get; set; }
        public virtual PrdSizingMRRMaster PrdSizingMRRMaster { get; set; }
        public virtual PrdWeavingMRRMaster PrdWeavingMRRMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdFinishingMRRShrinkage> PrdFinishingMRRShrinkages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdFinishingPackingList> PrdFinishingPackingLists { get; set; }
        public virtual CmnUser CmnUser { get; set; }
        public virtual CmnItemMaster CmnItemMaster { get; set; }
    }
}
