//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdFinishingMRRShrinkage
    {
        public long FinishingMRRShrinkageID { get; set; }
        public long FinishingMRRID { get; set; }
        public Nullable<decimal> ReqWeight { get; set; }
        public Nullable<decimal> FiniWeight { get; set; }
        public Nullable<decimal> AWWeight { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> SetID { get; set; }
        public Nullable<long> SizeMRRID { get; set; }
        public Nullable<long> WeavingMRRID { get; set; }
        public string GreigeEPIPPI { get; set; }
        public Nullable<decimal> FiniEPI { get; set; }
        public Nullable<decimal> FiniPPI { get; set; }
        public string AWEPIPPI { get; set; }
        public Nullable<decimal> CuttableWidth { get; set; }
        public Nullable<decimal> FiniWidth { get; set; }
        public Nullable<decimal> AWWidth { get; set; }
        public string WReqd { get; set; }
        public Nullable<decimal> LShrinkage { get; set; }
        public Nullable<decimal> WShrinkage { get; set; }
        public Nullable<decimal> FiniSkew { get; set; }
        public Nullable<bool> IsFSPercent { get; set; }
        public Nullable<decimal> AWSkew { get; set; }
        public Nullable<bool> IsAWPercent { get; set; }
        public Nullable<decimal> MovSkew { get; set; }
        public Nullable<bool> IsMovPercent { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual PrdFinishingMRRMaster PrdFinishingMRRMaster { get; set; }
    }
}
