//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdFinishingConsumptionMaster
    {
        public long FinishingConsumptionID { get; set; }
        public string FinishingConsumptionNo { get; set; }
        public Nullable<long> WeavingMRRID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> FinishingTypeID { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<System.DateTime> ConsumptionDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> TransactionTypeID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsReleased { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
