//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdPreCostingMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdPreCostingMaster()
        {
            this.PrdPreCostingDetails = new HashSet<PrdPreCostingDetail>();
            this.PrdPreCostingDyings = new HashSet<PrdPreCostingDying>();
            this.PrdPreCostingFinishings = new HashSet<PrdPreCostingFinishing>();
            this.PrdPreCostingSizes = new HashSet<PrdPreCostingSize>();
            this.PrdPreCostingYarns = new HashSet<PrdPreCostingYarn>();
        }
    
        public long CostingID { get; set; }
        public string CostingNo { get; set; }
        public Nullable<System.DateTime> CostingDate { get; set; }
        public Nullable<long> BOMID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusOn { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual AccCurrencyInfo AccCurrencyInfo { get; set; }
        public virtual PrdBOMMaster PrdBOMMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdPreCostingDetail> PrdPreCostingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdPreCostingDying> PrdPreCostingDyings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdPreCostingFinishing> PrdPreCostingFinishings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdPreCostingSize> PrdPreCostingSizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdPreCostingYarn> PrdPreCostingYarns { get; set; }
        public virtual CmnItemMaster CmnItemMaster { get; set; }
    }
}
