//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdSetSetup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdSetSetup()
        {
            this.PrdDyingMRRSetDetails = new HashSet<PrdDyingMRRSetDetail>();
            this.PrdInternalIssues = new HashSet<PrdInternalIssue>();
            this.PrdSizingBeamIssues = new HashSet<PrdSizingBeamIssue>();
            this.PrdSizingChemicalConsumptions = new HashSet<PrdSizingChemicalConsumption>();
            this.PrdSizingChemicalSetups = new HashSet<PrdSizingChemicalSetup>();
            this.PrdWeavingLoomDetailDatas = new HashSet<PrdWeavingLoomDetailData>();
            this.PrdWeavingMachineBooks = new HashSet<PrdWeavingMachineBook>();
        }
    
        public long SetID { get; set; }
        public string SetNo { get; set; }
        public long SetMasterID { get; set; }
        public long ItemID { get; set; }
        public long YarnID { get; set; }
        public string YarnCount { get; set; }
        public string YarnRatioLot { get; set; }
        public string YarnRatio { get; set; }
        public Nullable<int> SetTrackingNo { get; set; }
        public Nullable<int> NoOfBall { get; set; }
        public Nullable<long> SetLength { get; set; }
        public Nullable<decimal> MachineSpeed { get; set; }
        public Nullable<decimal> TotalEnds { get; set; }
        public string Weave { get; set; }
        public Nullable<decimal> EndsPerRope { get; set; }
        public Nullable<decimal> EndsPerCreel { get; set; }
        public Nullable<decimal> LeaseReapet { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> BuyerID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<long> WeftYarnID { get; set; }
        public Nullable<long> WarpYarnID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SetDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsSampleSet { get; set; }
        public Nullable<bool> IsBallComplete { get; set; }
        public Nullable<bool> IsDyeComplete { get; set; }
        public Nullable<bool> IsLCBComplete { get; set; }
        public Nullable<bool> IsSizeComplete { get; set; }
        public Nullable<bool> IsWeavingComplete { get; set; }
        public Nullable<bool> IsFinishingComplete { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnItemMaster CmnItemMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdDyingMRRSetDetail> PrdDyingMRRSetDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdInternalIssue> PrdInternalIssues { get; set; }
        public virtual PrdSetMaster PrdSetMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingBeamIssue> PrdSizingBeamIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingChemicalConsumption> PrdSizingChemicalConsumptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingChemicalSetup> PrdSizingChemicalSetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingLoomDetailData> PrdWeavingLoomDetailDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingMachineBook> PrdWeavingMachineBooks { get; set; }
    }
}
