//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdSizingMRRDetail
    {
        public long SizeMRRDetailID { get; set; }
        public long SizeMRRID { get; set; }
        public Nullable<int> OutputUnitID { get; set; }
        public Nullable<long> SizeMachineStopMasterID { get; set; }
        public Nullable<int> TotalStop { get; set; }
        public Nullable<long> SizeBreakageMasterID { get; set; }
        public Nullable<int> TotalBCBreakage { get; set; }
        public Nullable<int> TotalHSBreakage { get; set; }
        public Nullable<decimal> SqueezingActual { get; set; }
        public Nullable<decimal> OverallStretch { get; set; }
        public Nullable<decimal> SqueezingSTD { get; set; }
        public Nullable<decimal> BeamLength { get; set; }
        public Nullable<int> BeamQualityID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> MachineSpeed { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<int> ShiftEngineerID { get; set; }
        public string Remarks { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual PrdOutputUnit PrdOutputUnit { get; set; }
        public virtual PrdSizingMRRMaster PrdSizingMRRMaster { get; set; }
    }
}
