//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdSizingMRRMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdSizingMRRMaster()
        {
            this.PrdSizingMRRDetails = new HashSet<PrdSizingMRRDetail>();
            this.PrdWeavingMachineBooks = new HashSet<PrdWeavingMachineBook>();
            this.PrdFinishingMRRMasters = new HashSet<PrdFinishingMRRMaster>();
            this.PrdSizingBeamIssues = new HashSet<PrdSizingBeamIssue>();
            this.PrdWeavingLoomDetailDatas = new HashSet<PrdWeavingLoomDetailData>();
        }
    
        public long SIzeMRRID { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public string SizeMRRNo { get; set; }
        public Nullable<long> MachineID { get; set; }
        public System.DateTime SizeMRRDate { get; set; }
        public long ItemID { get; set; }
        public Nullable<long> SetID { get; set; }
        public string Description { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
        public Nullable<bool> IsIssued { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingMRRDetail> PrdSizingMRRDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingMachineBook> PrdWeavingMachineBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdFinishingMRRMaster> PrdFinishingMRRMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingBeamIssue> PrdSizingBeamIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingLoomDetailData> PrdWeavingLoomDetailDatas { get; set; }
    }
}
