//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdSetMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdSetMaster()
        {
            this.PrdSetSetups = new HashSet<PrdSetSetup>();
        }
    
        public long SetMasterID { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<System.DateTime> SetDate { get; set; }
        public long ItemID { get; set; }
        public Nullable<decimal> PIItemlength { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> BuyerID { get; set; }
        public Nullable<long> RefSetID { get; set; }
        public Nullable<System.DateTime> RefSetDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSetSetup> PrdSetSetups { get; set; }
    }
}
