//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdSizingBeamIssueDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdSizingBeamIssueDetail()
        {
            this.PrdWeavingMachineBooks = new HashSet<PrdWeavingMachineBook>();
        }
    
        public long BeamIssueDetailID { get; set; }
        public Nullable<long> BeamIssueID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<int> BeamID { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<System.DateTime> BSDate { get; set; }
        public Nullable<System.DateTime> BMDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> LoomID { get; set; }
        public Nullable<decimal> Totalfabric { get; set; }
        public Nullable<System.DateTime> BFDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual PrdOutputUnit PrdOutputUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingMachineBook> PrdWeavingMachineBooks { get; set; }
        public virtual PrdSizingBeamIssue PrdSizingBeamIssue { get; set; }
    }
}
