//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdSizingChemicalconsumptionDetail
    {
        public long ChemicalConsumptionDetailID { get; set; }
        public long ChemicalConsumptionID { get; set; }
        public long ChemicalID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public int UnitID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> BatchID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ConsumptionDate { get; set; }
        public Nullable<long> TransactionTypeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnItemMaster CmnItemMaster { get; set; }
        public virtual CmnUOM CmnUOM { get; set; }
        public virtual PrdSizingChemicalConsumption PrdSizingChemicalConsumption { get; set; }
    }
}
