//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdSizingBeamIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdSizingBeamIssue()
        {
            this.PrdSizingBeamIssueDetails = new HashSet<PrdSizingBeamIssueDetail>();
        }
    
        public long BeamIssueID { get; set; }
        public int TransactionTypeID { get; set; }
        public string BeamIssueNo { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<decimal> Setlength { get; set; }
        public Nullable<long> SetID { get; set; }
        public Nullable<long> SizeMRRID { get; set; }
        public Nullable<int> SizeDepartmentID { get; set; }
        public Nullable<int> WeavingDepartmentID { get; set; }
        public Nullable<bool> IsIssuedSize { get; set; }
        public Nullable<System.DateTime> SizeIssueDate { get; set; }
        public Nullable<int> SizeIssueBy { get; set; }
        public string SizeIssueRemarks { get; set; }
        public Nullable<bool> IsReceivedWeaving { get; set; }
        public Nullable<System.DateTime> WeavingReceiveDate { get; set; }
        public Nullable<int> WeavingReceiveBy { get; set; }
        public string WeavingReceivedRemarks { get; set; }
        public string Shade { get; set; }
        public string GPL { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual PrdSizingMRRMaster PrdSizingMRRMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdSizingBeamIssueDetail> PrdSizingBeamIssueDetails { get; set; }
        public virtual CmnItemMaster CmnItemMaster { get; set; }
        public virtual PrdSetSetup PrdSetSetup { get; set; }
    }
}
