//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdWeavingMachinConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrdWeavingMachinConfig()
        {
            this.PrdWeavingMachineBooks = new HashSet<PrdWeavingMachineBook>();
            this.PrdWeavingMachineConfigDetails = new HashSet<PrdWeavingMachineConfigDetail>();
            this.MntMachineMaintenanceOrders = new HashSet<MntMachineMaintenanceOrder>();
            this.PrdWeavingLoomDetailDatas = new HashSet<PrdWeavingLoomDetailData>();
            this.CmnItemMasters = new HashSet<CmnItemMaster>();
            this.MntMachineScheduleDetails = new HashSet<MntMachineScheduleDetail>();
        }
    
        public long MachineConfigID { get; set; }
        public string MachineConfigNo { get; set; }
        public Nullable<long> MachineID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> LineID { get; set; }
        public string Remarks { get; set; }
        public bool IsBook { get; set; }
        public bool IsCorrupted { get; set; }
        public bool IsMaintenance { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnOrganogram CmnOrganogram { get; set; }
        public virtual PrdWeavingLine PrdWeavingLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingMachineBook> PrdWeavingMachineBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingMachineConfigDetail> PrdWeavingMachineConfigDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MntMachineMaintenanceOrder> MntMachineMaintenanceOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdWeavingLoomDetailData> PrdWeavingLoomDetailDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmnItemMaster> CmnItemMasters { get; set; }
        public virtual CmnItemMaster CmnItemMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MntMachineScheduleDetail> MntMachineScheduleDetails { get; set; }
    }
}
