//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdWeavingMachineBook
    {
        public long MachineBookID { get; set; }
        public long MachineConfigID { get; set; }
        public Nullable<long> BeamIssueDetailID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> SetID { get; set; }
        public Nullable<long> SizeMRRID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public bool IsReleased { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Remarks { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual PrdSizingBeamIssueDetail PrdSizingBeamIssueDetail { get; set; }
        public virtual PrdSizingMRRMaster PrdSizingMRRMaster { get; set; }
        public virtual PrdWeavingMachinConfig PrdWeavingMachinConfig { get; set; }
        public virtual PrdSetSetup PrdSetSetup { get; set; }
    }
}
