//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdWeavingLoomDetailData
    {
        public long LoomRecordDetailID { get; set; }
        public long LoomRecordID { get; set; }
        public Nullable<long> MachineConfigID { get; set; }
        public Nullable<long> SetID { get; set; }
        public Nullable<long> SizeMRRID { get; set; }
        public Nullable<long> LoomStopID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<decimal> WarpStop { get; set; }
        public Nullable<decimal> WarpCMPX { get; set; }
        public Nullable<decimal> WeftStop { get; set; }
        public Nullable<decimal> WeftCMPX { get; set; }
        public Nullable<decimal> OtherStop { get; set; }
        public Nullable<decimal> StartATT { get; set; }
        public Nullable<decimal> RPM { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> RunTime { get; set; }
        public Nullable<decimal> Prodn { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ShiftEngineerID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsReleased { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual HRMShift HRMShift { get; set; }
        public virtual PrdSizingMRRMaster PrdSizingMRRMaster { get; set; }
        public virtual PrdWeavingLoomStop PrdWeavingLoomStop { get; set; }
        public virtual PrdWeavingMachinConfig PrdWeavingMachinConfig { get; set; }
        public virtual PrdSetSetup PrdSetSetup { get; set; }
    }
}
