//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseCostAccessmentMaster
    {
        public long AccessmentCostID { get; set; }
        public string AccessmentNo { get; set; }
        public Nullable<System.DateTime> AccessmentDate { get; set; }
        public Nullable<long> POID { get; set; }
        public Nullable<long> RequisitionID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> CustomOfficeID { get; set; }
        public string AccessmentRefNo { get; set; }
        public Nullable<System.DateTime> AccessmentRefDate { get; set; }
        public string CustomRefNo { get; set; }
        public string DeclarantRefNo { get; set; }
        public Nullable<decimal> BondAmount { get; set; }
        public Nullable<decimal> BondDue { get; set; }
        public Nullable<decimal> SROAmount { get; set; }
        public Nullable<decimal> SRODue { get; set; }
        public string AccessmentDescription { get; set; }
        public string DocUrl { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
