//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseCostTransportMaster
    {
        public long TransportCostID { get; set; }
        public string TransportNo { get; set; }
        public Nullable<System.DateTime> TransportDate { get; set; }
        public Nullable<long> POID { get; set; }
        public Nullable<long> RequisitionID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> CarrierAgentID { get; set; }
        public Nullable<int> LoadingLocationID { get; set; }
        public Nullable<int> DischargeLocationID { get; set; }
        public string TransportDescription { get; set; }
        public string DocUrl { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
