//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseFR
    {
        public long FRID { get; set; }
        public string FRNo { get; set; }
        public Nullable<System.DateTime> FRDate { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<long> RequisitionID { get; set; }
        public string Purpose { get; set; }
        public string ExpanseBreakDown { get; set; }
        public Nullable<System.DateTime> FundShouldAvailableOn { get; set; }
        public Nullable<decimal> NegotiateOrderQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> CurrecncyID { get; set; }
        public Nullable<System.DateTime> EstimatedDate { get; set; }
        public Nullable<int> AvgLeadTime { get; set; }
        public Nullable<int> AdvisingBankID { get; set; }
        public int CompanyID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
