//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasePOMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchasePOMaster()
        {
            this.PurchasePODetails = new HashSet<PurchasePODetail>();
        }
    
        public long POID { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<long> RequisitionID { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<int> MoneyTransactionTypeID { get; set; }
        public string LCNo { get; set; }
        public string LCorVoucherorLcafNo { get; set; }
        public Nullable<System.DateTime> LCorVoucherorLcafDate { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> BankBranchID { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnCompany CmnCompany { get; set; }
        public virtual CmnOrganogram CmnOrganogram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasePODetail> PurchasePODetails { get; set; }
        public virtual InvRequisitionMaster InvRequisitionMaster { get; set; }
        public virtual CmnUser CmnUser { get; set; }
    }
}
