//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalBookingMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalBookingMaster()
        {
            this.SalBookingDetails = new HashSet<SalBookingDetail>();
            this.SalPIMasters = new HashSet<SalPIMaster>();
        }
    
        public long BookingID { get; set; }
        public string BookingNo { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> BuyerRefID { get; set; }
        public int EmployeeID { get; set; }
        public string Description { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusOn { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
        public Nullable<bool> IsPICompleted { get; set; }
        public Nullable<bool> IsLCCompleted { get; set; }
        public Nullable<bool> IsHDOCompleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalBookingDetail> SalBookingDetails { get; set; }
        public virtual CmnUser CmnUser { get; set; }
        public virtual CmnUser CmnUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPIMaster> SalPIMasters { get; set; }
    }
}
