//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalBookingDetail
    {
        public long BookingDetailID { get; set; }
        public long BookingID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> DeliveryStartDate { get; set; }
        public Nullable<System.DateTime> DeliveryFinishDate { get; set; }
        public Nullable<bool> IsDelevered { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusOn { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual SalBookingMaster SalBookingMaster { get; set; }
        public virtual CmnItemMaster CmnItemMaster { get; set; }
    }
}
