//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalFDOMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalFDOMaster()
        {
            this.SalFDODetails = new HashSet<SalFDODetail>();
        }
    
        public long FDOMasterID { get; set; }
        public string FDONo { get; set; }
        public System.DateTime FDODate { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public string HDOID { get; set; }
        public int PartyID { get; set; }
        public string DeliveryTo { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string TruckNo { get; set; }
        public string BuyerContactName { get; set; }
        public string BuyerContactPhoneNo { get; set; }
        public string DriverName { get; set; }
        public string DriverPhoneNo { get; set; }
        public Nullable<bool> IsDCCompleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalFDODetail> SalFDODetails { get; set; }
    }
}
