//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalHDODetail
    {
        public long HDODetailID { get; set; }
        public long HDOID { get; set; }
        public Nullable<long> PIID { get; set; }
        public long ProductID { get; set; }
        public Nullable<short> ItemConstructionTypeID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> RemainingQty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsOriginal { get; set; }
        public Nullable<bool> IsDC { get; set; }
        public Nullable<long> OriginalDOMasterID { get; set; }
        public Nullable<bool> IsFDOCompleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
