//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalHDOMaster
    {
        public long HDOID { get; set; }
        public string HDONo { get; set; }
        public Nullable<System.DateTime> HDODate { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<int> LCID { get; set; }
        public string AHDONo { get; set; }
        public Nullable<decimal> AHDOQTY { get; set; }
        public Nullable<int> RevisionNo { get; set; }
        public long OriginalDOMasterID { get; set; }
        public Nullable<int> HSPin { get; set; }
        public string B2BLCNo { get; set; }
        public Nullable<System.DateTime> B2BLCDate { get; set; }
        public string UPNo { get; set; }
        public string Beneficiary { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<bool> IsAllApproved { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> DeclinedBy { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnOrganogram CmnOrganogram { get; set; }
    }
}
