//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalLCMaster
    {
        public long LCID { get; set; }
        public string LCNo { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public string ExportLCNo { get; set; }
        public string LCReferenceNo { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> RefNoDate { get; set; }
        public Nullable<System.DateTime> LCDate { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> CircularNoDate { get; set; }
        public Nullable<System.DateTime> ExportLCNoDate { get; set; }
        public Nullable<int> DocPrepDays { get; set; }
        public Nullable<bool> IsMasterLC { get; set; }
        public string MasterLCNO { get; set; }
        public Nullable<int> LCOpenBank { get; set; }
        public Nullable<int> LCOpenBranch { get; set; }
        public Nullable<int> LCMasterBank { get; set; }
        public Nullable<int> LCMasterBranch { get; set; }
        public Nullable<decimal> ODInterest { get; set; }
        public string GarmentsQTY { get; set; }
        public Nullable<decimal> LCAmount { get; set; }
        public Nullable<int> LCCurrencyID { get; set; }
        public Nullable<int> LocalCurrencyID { get; set; }
        public string IRCNo { get; set; }
        public string SalesContractNo { get; set; }
        public string CircularNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Sight { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string VATRegNo { get; set; }
        public string CentralBankRefNo { get; set; }
        public Nullable<bool> IsHDOCompleted { get; set; }
        public string AmendmentNo { get; set; }
        public Nullable<System.DateTime> AmendmentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual CmnOrganogram CmnOrganogram { get; set; }
    }
}
