//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalPIMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalPIMaster()
        {
            this.PrdDyingMRRSetDetails = new HashSet<PrdDyingMRRSetDetail>();
            this.PrdFinishingPackingLists = new HashSet<PrdFinishingPackingList>();
            this.SalLCDetails = new HashSet<SalLCDetail>();
            this.SalPIDetails = new HashSet<SalPIDetail>();
        }
    
        public long PIID { get; set; }
        public string PINO { get; set; }
        public System.DateTime PIDate { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<long> BookingID { get; set; }
        public Nullable<short> IncotermID { get; set; }
        public string IncotermDescription { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ShipmentID { get; set; }
        public Nullable<int> PayDay { get; set; }
        public Nullable<int> ValidityID { get; set; }
        public Nullable<int> NegoDay { get; set; }
        public Nullable<int> SightID { get; set; }
        public Nullable<decimal> ODInterest { get; set; }
        public int BuyerID { get; set; }
        public Nullable<short> AcceptanceID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> AdvisingBankID { get; set; }
        public Nullable<int> SalesPersionPin { get; set; }
        public Nullable<bool> IsLcCompleted { get; set; }
        public Nullable<bool> IsHDOCompleted { get; set; }
        public int CompanyID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusOn { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdDyingMRRSetDetail> PrdDyingMRRSetDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrdFinishingPackingList> PrdFinishingPackingLists { get; set; }
        public virtual SalBookingMaster SalBookingMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalLCDetail> SalLCDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPIDetail> SalPIDetails { get; set; }
    }
}
