//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalPPBillingMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalPPBillingMaster()
        {
            this.SalPPBAMasters = new HashSet<SalPPBAMaster>();
        }
    
        public long BillMasterId { get; set; }
        public long LCID { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> TypeOfDocs { get; set; }
        public Nullable<decimal> DeliveryQty { get; set; }
        public Nullable<decimal> DeliveryValue { get; set; }
        public string DocsNo { get; set; }
        public Nullable<System.DateTime> DocsDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> DocsRecievedDateFromFactory { get; set; }
        public Nullable<System.DateTime> DocsSentDateToParty { get; set; }
        public Nullable<System.DateTime> PartyAcceptanceDate { get; set; }
        public Nullable<int> NegotiatingBank { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> SubmissionDateToPartyBank { get; set; }
        public Nullable<System.DateTime> BankAcceptanceDate { get; set; }
        public Nullable<System.DateTime> PurchaseDiscountDate { get; set; }
        public Nullable<decimal> LIB { get; set; }
        public Nullable<decimal> LIBDiscount { get; set; }
        public Nullable<decimal> ConversionRate { get; set; }
        public Nullable<decimal> ConvertionPercentage { get; set; }
        public Nullable<decimal> SugarPAD { get; set; }
        public Nullable<decimal> LIBRateOfInterest { get; set; }
        public Nullable<decimal> ReserveMargin { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<System.DateTime> PaymentIssueDate { get; set; }
        public Nullable<decimal> PaymentValue { get; set; }
        public Nullable<int> ModeOfPayment { get; set; }
        public Nullable<decimal> Shortfall { get; set; }
        public Nullable<decimal> ODAdjust { get; set; }
        public Nullable<System.DateTime> PaymentReceivedDate { get; set; }
        public Nullable<System.DateTime> BankAdjustmentDate { get; set; }
        public Nullable<int> PartyODDays { get; set; }
        public Nullable<int> BankODDays { get; set; }
        public Nullable<decimal> PartyODInterest { get; set; }
        public Nullable<decimal> BankODInterest { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<long> SerialNo { get; set; }
        public Nullable<bool> IsDocs { get; set; }
        public Nullable<bool> IsPurchase { get; set; }
        public Nullable<bool> IsOD { get; set; }
        public Nullable<bool> IsAdjust { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public Nullable<System.DateTime> StatusOn { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalPPBAMaster> SalPPBAMasters { get; set; }
        public virtual CmnCompany CmnCompany { get; set; }
    }
}
