//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalPPBAMaster
    {
        public long BAID { get; set; }
        public long BillID { get; set; }
        public string AdjustmentNo { get; set; }
        public Nullable<decimal> LIBAdjustmentAmount { get; set; }
        public Nullable<decimal> RestRealizedAmount { get; set; }
        public string PAD { get; set; }
        public Nullable<decimal> RestRealizedAmountPercent { get; set; }
        public Nullable<System.DateTime> AdjustmentDate { get; set; }
        public string ERQ { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    
        public virtual SalPPBillingMaster SalPPBillingMaster { get; set; }
        public virtual CmnCompany CmnCompany { get; set; }
    }
}
