//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalSalesInvoiceMaster
    {
        public long SIID { get; set; }
        public string SINo { get; set; }
        public Nullable<System.DateTime> SIDate { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public Nullable<int> SITypeID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
