//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesItem
    {
        public int SaleItemID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_Sales tbl_Sales { get; set; }
    }
}
