//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Sales()
        {
            this.tbl_SalesItem = new HashSet<tbl_SalesItem>();
        }
    
        public int SaleID { get; set; }
        public string SaleNo { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> OutletID { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual tbl_ProductOutlet tbl_ProductOutlet { get; set; }
        public virtual tbl_ProductType tbl_ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SalesItem> tbl_SalesItem { get; set; }
    }
}
