//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ABS.Models;

namespace ABS.Web.ViewModels
{
    public partial class ViewModelVoucherType
    {
        //public EmVoucherType()
        //{
        //    this.VoucherMasters = new HashSet<VoucherMaster>();
        //}

        public int Id { get; set; }
        [Display(Name = "Voucher Type")]
        public string VoucherTypeName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }

        public virtual ICollection<AccVoucherMaster> VoucherMasters { get; set; }


        public AccVoucherType VoucherTypeEntity()
        {
            var obj = new AccVoucherType();
            obj.Id = this.Id;
            obj.VoucherTypeName = this.VoucherTypeName;
            obj.Description = this.Description;

            obj.IsActive = this.IsActive;

            return obj;


        }

    }
}