//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using ABS.Models;

namespace ABS.Web.ViewModels
{
    public class ViewModelAC2
    {
        //public AC2()
        //{
        //    this.AC3 = new HashSet<AC3>();
        //}
    [DisplayName("Level-1")]
    [Required(ErrorMessage = "This field is required.")]
        public int AC1Id { get; set; }
        public int Id { get; set; }
          [DisplayName("Level-2")]
          [Required(ErrorMessage = "Name is required.")]
        [Remote("IsNameAvailble2", "AC3", ErrorMessage = "Name Already Exist.")]
        public string AC2Name { get; set; }

           [DisplayName("Level-2 Code")]
           [Required(ErrorMessage = "Code is required.")]
        public string AC2ManualCode { get; set; }
        public Nullable<bool> Transfered { get; set; }
        public int AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsActive { get; set; }

      //  public virtual ViewModelAC1 vmAC1 { get; set; }
      //  public virtual ICollection<AC3> AC3 { get; set; }
          [DisplayName("Level-1")]
        public string AC1Name { get; set; }


        public AccAC2 viewModelEntity()
        {
            var ac2 = new AccAC2();
        ac2.AC1Id = this.AC1Id;
        ac2.Id = this.Id;
        ac2.AC2Name = this.AC2Name;
        ac2.AC2ManualCode = this.AC2ManualCode;
        ac2.Transfered = this.Transfered;
        ac2.AddedBy = this.AddedBy;
        ac2.DateAdded = this.DateAdded;
        ac2.UpdatedBy = this.UpdatedBy;
        ac2.DateUpdated = this.DateUpdated;
        ac2.IsActive = this.IsActive;


        return ac2;
        }

    }
}
