//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using ABS.Models;

namespace ABS.Web.ViewModels
{
    public class ViewModelVoucherDetail
    {
        public int Id { get; set; }
        public int VMasterId { get; set; }
        public string VoucherNo { get; set; }
       [Required(ErrorMessage = "CostCenter is required.")]
        public int? CostCenterId { get; set; }
       [Required(ErrorMessage = "Account Ledger is required.")]
        public int AC5Id { get; set; }
         [Required(ErrorMessage = "DebitAmount is required.")]
        public decimal DebitAmount { get; set; }
          [Required(ErrorMessage = "DebitAmount is required.")]
        public decimal CreditAmount { get; set; }
        public string Others { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TransactionType { get; set; }

        public virtual AccACDetail ACDetail { get; set; }
      
        public virtual AccCostCenterInfo CostCenterInfo { get; set; }
        public virtual AccVoucherMaster VoucherMaster { get; set; }



        public AccVoucherDetail VoucherDetailEntity()
        {

            var objVDetail = new AccVoucherDetail();

            objVDetail.Id = this.Id;
            objVDetail.VMasterId = this.VMasterId;
            objVDetail.VoucherNo = this.VoucherNo;
            objVDetail.CostCenterId = this.CostCenterId;
            objVDetail.AC5Id = this.AC5Id;
            objVDetail.DebitAmount = this.DebitAmount;
            objVDetail.CreditAmount = this.CreditAmount;
            objVDetail.Others = this.Others;
            objVDetail.IsActive = this.IsActive;
            objVDetail.TransactionType = this.TransactionType;

            return objVDetail;



        }
    }
}