//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABS.Models;
using ABS.Web.Utility;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ABS.Web.ViewModels
{
    public class ViewModelAC3
    {
        [DisplayName("Level-1")]
        [Required(ErrorMessage = "This field is required.")]

        public int AC1Id { get; set; }
        [DisplayName("Level-2")]
        [Required(ErrorMessage = "This field is required.")]

        public int AC2Id { get; set; }
        public int Id { get; set; }

        [DisplayName("Level-3")]
        [Required(ErrorMessage = "Name is required.")]
        [Remote("IsNameAvailble3", "AC3", ErrorMessage = "Name Already Exist.")]

        public string AC3Name { get; set; }


        [DisplayName("Level-2")]
        public string AC2Name { get; set; }


        [DisplayName("Level-1")]
        public string AC1Name { get; set; }


        [DisplayName("Level-3 Code")]
        [Required(ErrorMessage = "Code is required.")]

        public string AC3ManualCode { get; set; }
        public Nullable<bool> Transfered { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public bool IsActive { get; set; }
        [DisplayName("Is Level Completed")]
        public bool IsAccountLedger { get; set; }

        public virtual AccAC2 AC2 { get; set; }
        public virtual ICollection<AccAC4> AC4 { get; set; }
        public string AC4Name { get; set; }


        //private void MakeAc3(AccAC3 aC3)
        //{
        //    var autoNumber = UniqueCode.GetAutoNumber("AC3");
        //    aC3.Id = Convert.ToInt32(autoNumber);
        //    aC3.AC3ManualCode = UniqueCode.GetAccountLedgerCode("AL3", autoNumber);
        //    aC3.IsActive = true;
        //    aC3.Transfered = false;
        //    aC3.DateAdded = DateTime.Now;
        //    aC3.AddedBy = Convert.ToInt32();
        //    aC3.DateUpdated = DateTime.Now;
        //    aC3.UpdatedBy = Convert.ToInt32(Session["UserID"]);
        //}

        public AccAC3 AC3Entity()
        {

            var objAC3 = new AccAC3();
            objAC3.AC1Id = this.AC1Id;
            objAC3.AC2Id = this.AC2Id;
            objAC3.Id = this.Id;
            objAC3.AC3Name = this.AC3Name;
            objAC3.AC3ManualCode = this.AC3ManualCode;
            objAC3.Transfered = this.Transfered;
            objAC3.AddedBy = this.AddedBy;
            objAC3.DateAdded = this.DateAdded;
            objAC3.UpdatedBy = this.UpdatedBy;
            objAC3.DateUpdated = this.DateUpdated;
            objAC3.IsActive = this.IsActive;
            objAC3.IsAccountLedger = this.IsAccountLedger;

            return objAC3;


        }

        public AccAC3 MakeAc3(int userId)
        {
            var aC3 = AC3Entity();
            var autoNumber = UniqueCode.GetAutoNumber("AC3");
            aC3.Id = Convert.ToInt32(autoNumber);
            aC3.AC3ManualCode = UniqueCode.GetAccountLedgerCode("AL3", autoNumber);
            aC3.IsActive = true;
            aC3.Transfered = false;
            aC3.DateAdded = DateTime.Now;
            aC3.AddedBy = userId;
            aC3.DateUpdated = DateTime.Now;
            aC3.UpdatedBy = userId;

            return aC3;


        }

    }
}
